### ISSUE TITLE
Error: Invalid URI

### ISSUE THREAD

**Issue by axi92** [iloire/watchmen#106]
I have no clue what is wrong.
With this settings:
![grafik](https://user-images.githubusercontent.com/1394837/43197704-3f8ae740-900c-11e8-988f-8b7e5ffb0e1f.png)

I get this:
`Localhost-watchmen is still down!. Error: {}`

Is there a debug function? Or some logs?

**Comment by axi92** [comment]
Ok I modified the watchmen.js to get a better error message and now I get this:

```
watchmen has started. 1 services loaded

Error: Invalid URI "127.0.0.1"
    at Request.init (/home/plehner/Schreibtisch/watchmen/node_modules/request/request.js:273:31)
    at new Request (/home/plehner/Schreibtisch/watchmen/node_modules/request/request.js:127:8)
    at request (/home/plehner/Schreibtisch/watchmen/node_modules/request/index.js:53:10)
    at Function.get (/home/plehner/Schreibtisch/watchmen/node_modules/request/index.js:61:12)
    at PingService.ping (/home/plehner/Schreibtisch/watchmen/node_modules/watchmen-ping-http-head/index.js:23:11)
    at WatchMen.ping (/home/plehner/Schreibtisch/watchmen/lib/watchmen.js:42:23)
    at WatchMen._launch (/home/plehner/Schreibtisch/watchmen/lib/watchmen.js:160:8)
    at Timeout._onTimeout (/home/plehner/Schreibtisch/watchmen/lib/watchmen.js:192:14)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
Localhost-watchmen check failed!. Error: {"error":{},"currentFailureCount":66}
Localhost-watchmen is still down!. Error: {}
```

**Comment by axi92** [comment]
Ok I found out that it needs the protocol: `http://`

**Comment by axi92** [comment]
The second error that I got was `UNABLE_TO_VERIFY_LEAF_SIGNATURE`
But I was able to fix that although it is not a secure fix according to this: https://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

I just added `process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';` to `/home/plehner/Schreibtisch/watchmen/lib/watchmen.js`
