### ISSUE TITLE
Error: ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by mani-ae** [iloire/watchmen#108]
Am getting this error while running the web-server

PS C:\Projects\Source\Repos\watchmen> node run-web-server.js
Using storage env:  development
watchmen server listening on port 3000 in development mode
Error: ERR wrong number of arguments for 'set' command
    at ReplyParser.<anonymous> (C:\Projects\Source\Repos\watchmen\node_modules\redis\index.js:317:31)
    at ReplyParser.emit (events.js:182:13)
    at ReplyParser.send_error (C:\Projects\Source\Repos\watchmen\node_modules\redis\lib\parser\javascript.js:296:10)
    at ReplyParser.execute (C:\Projects\Source\Repos\watchmen\node_modules\redis\lib\parser\javascript.js:181:22)
    at RedisClient.on_data (C:\Projects\Source\Repos\watchmen\node_modules\redis\index.js:547:27)
    at Socket.<anonymous> (C:\Projects\Source\Repos\watchmen\node_modules\redis\index.js:102:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)

**Comment by mani-ae** [comment]
This is resolved after i installed newer version of Redis
