### ISSUE TITLE
Google+ API Sunset

### ISSUE THREAD

**Issue by nysky1** [iloire/watchmen#112]
With the sunset of the Google+ API, this breaks Watchmen's authentication.

**Comment by lapo-luchini** [comment]
Just in case someone is searching by string, this produces an error like this:
```
InternalOAuthError: failed to fetch user profile
    at …/node_modules/passport-google-oauth2/lib/oauth2.js:92:28
    at passBackControl (…/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (…/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
