### ISSUE TITLE
InternalOAuthError 

### ISSUE THREAD

**Issue by TakeMeNL** [iloire/watchmen#62]
Running docker-composer filled in the google dev stuff tested and gave me 500 internal error

```
watchmenweb_1     | InternalOAuthError: failed to fetch user profile
watchmenweb_1     |     at /watchmen/node_modules/passport-google-oauth2/lib/oauth2.js:92:28
watchmenweb_1     |     at passBackControl (/watchmen/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
watchmenweb_1     |     at IncomingMessage.<anonymous> (/watchmen/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
watchmenweb_1     |     at emitNone (events.js:72:20)
watchmenweb_1     |     at IncomingMessage.emit (events.js:166:7)
watchmenweb_1     |     at endReadableNT (_stream_readable.js:913:12)
watchmenweb_1     |     at nextTickCallbackWith2Args (node.js:442:9)
watchmenweb_1     |     at process._tickCallback (node.js:356:17)
```

**Comment by TakeMeNL** [comment]
Oke so i enabled the Google+ API and reset all docker images by building from scratch and now its working!
