### ISSUE TITLE
Google auth internal server error

### ISSUE THREAD

**Issue by philnord** [iloire/watchmen#71]
Hi, I set up the credentials for GA but get a 500 when performing the authentication.

Redirect URLs setup correctly.

InternalOAuthError: failed to fetch user profile
    at /var/www/watchmen/node_modules/passport-google-oauth2/lib/oauth2.js:92:28
    at passBackControl (/var/www/watchmen/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/var/www/watchmen/node_modules/passport-google-oauth2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Seen this before?

**Comment by syamsathyan** [comment]
Go to google developer console and enable the Google+ api

**Comment by philnord** [comment]
Thanks!
